[package]
name = "rt"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
assert_approx_eq = "1.1.0"
clap = { version = "4.1.3", features = ["derive"] }
serde = { version = "1.0.152", features = ["derive"] }
typetag = "0.2.5"
ron = "0.8.0"