[package]
name = "raytracer"
version = "0.1.0"
authors = ["daibou ba'zer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.27"
png = "0.15.0"
rand = "0.3"
threadpool = "1.7"
